# syntax=docker/dockerfile:1
FROM golang:1.25.4-alpine AS builder

# Installation des outils de build C
RUN apk add --no-cache gcc musl-dev

WORKDIR /app

# 1. Cache des dépendances Go
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

# 2. Cache de compilation (GOCACHE)
# On utilise --mount pour garder les fichiers .a et ne pas recompiler sqlite à chaque fois
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=1 GOOS=linux go build -ldflags '-linkmode external -extldflags "-static"' -o server main.go

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /root/
COPY --from=builder /app/server .
COPY --from=builder /app/templates ./templates
EXPOSE 8080
CMD ["./server"]